# Generated by Django 4.1.7 on 2023-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_district_delete_branchs_alter_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(default='Ernakulam', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Aluva', max_length=100),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
