# Generated by Django 4.1.7 on 2023-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_alter_branch_district_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('acc_type', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('debit', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('cheque', models.BooleanField(default=False)),
            ],
        ),
    ]
