# Generated by Django 4.1.7 on 2023-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_details_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_info',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details_info',
            name='cheque',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='details_info',
            name='credit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='details_info',
            name='debit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
